#!/usr/bin/env zsh
# temple-project-map.zsh — temple project map (P0) — shared across machines
#
# ⚠ GENERATED FILE — do NOT hand-edit the TEMPLE_PROJECT_MAP array below.
#   Source of truth : registries/projects.json
#   Regenerated by  : registries/gen-temple-map.sh (run by deploy.sh before the zsh rsync)
#   To change a path: edit projects.json, then deploy. (decision 0008/0004, amended
#   2026-08-15 — physical paths moved from this array into the JSON registry so
#   registry data lives in a registry file and the zsh stays a clean executive.)
#
# folder layout is 1:1 on office and home; paths are identical on both hosts.
# companion: reposoma/registry/index.md — logical project map; projects.json holds physical paths.
# rule: source this file; do NOT hard-code these paths elsewhere.

typeset -gA TEMPLE_PROJECT_MAP
TEMPLE_PROJECT_MAP=(
  [reposoma]="/home/hruzam/reposoma"
  [subai.devenv]="/home/hruzam/www/ovum/subai.devenv"
  [reposoma.devenv]="/home/hruzam/www/ovum/reposoma.devenv"
  [freya]="/home/hruzam/www/imago_cz/freya"
  [freya.devenv]="/home/hruzam/www/imago_cz/freya.devenv"
  [piql.dev]="/home/hruzam/www/piql/piql.dev"
  [vacuole]="/home/hruzam/vacuole"
  [fantasyobchod]="/home/hruzam/www/imago_cz/fantasyobchod"
  [psdvsSys]="/home/hruzam/www/psdvs/psdvsSys"
  [applications-in-common]="/home/hruzam/www/elements-factory/applications-in-common"
  [nablarva]="/home/hruzam/unikuklatrix/nablarva"
  [nablarva.devenv]="/home/hruzam/unikuklatrix/nablarva.devenv"
  [termbrana]="/home/hruzam/unikuklatrix/termbrana"
)

# temple-project-root <project-name>
# Resolves a logical project name to its repo-root on this host.
# Exits non-zero and prints to stderr if unknown.
temple-project-root() {
  local name="$1"
  local root="${TEMPLE_PROJECT_MAP[$name]}"
  if [[ -z "$root" ]]; then
    print -u2 "temple-project-map: unknown project '$name' on host ${MACHINE_NAME:-unknown}"
    return 1
  fi
  if [[ ! -d "$root" ]]; then
    print -u2 "temple-project-map: project '$name' maps to '$root' but directory not found on this host"
    return 2
  fi
  print -- "$root"
}
