#!/usr/bin/env bash
# gen-temple-map.sh — regenerate ai/temple-project-map.zsh from registries/projects.json.
#
# Single source of truth for physical repo-root paths = registries/projects.json
# (decision 0008/0004, amended 2026-08-15: paths moved out of the zsh array into JSON).
# This script GENERATES the zsh artifact so the shell needs NO jq at startup — the
# array is baked at deploy time. deploy.sh calls this before the ~/.config/zsh rsync.
#
# The temple-project-root() function body is preserved verbatim — consumers unchanged.
#
# Usage:
#   gen-temple-map.sh            regenerate ai/temple-project-map.zsh (writes)
#   gen-temple-map.sh --check    exit 3 if the artifact is stale vs projects.json (no write)
#   gen-temple-map.sh --stdout   print generated content to stdout (no write)
set -euo pipefail

REPO_ZSH="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"   # .../ia-sync/zsh
SRC="$REPO_ZSH/registries/projects.json"
OUT="$REPO_ZSH/ai/temple-project-map.zsh"

MODE="write"
case "${1:-}" in
  --check)  MODE="check" ;;
  --stdout) MODE="stdout" ;;
  "")       MODE="write" ;;
  *) echo "usage: gen-temple-map.sh [--check|--stdout]" >&2; exit 2 ;;
esac

command -v jq >/dev/null || { echo "gen-temple-map: jq required" >&2; exit 1; }
[ -f "$SRC" ] || { echo "gen-temple-map: missing $SRC" >&2; exit 1; }

render() {
  cat <<'HEADER'
#!/usr/bin/env zsh
# temple-project-map.zsh — temple project map (P0) — shared across machines
#
# ⚠ GENERATED FILE — do NOT hand-edit the TEMPLE_PROJECT_MAP array below.
#   Source of truth : registries/projects.json
#   Regenerated by  : registries/gen-temple-map.sh (run by deploy.sh before the zsh rsync)
#   To change a path: edit projects.json, then deploy. (decision 0008/0004, amended
#   2026-08-15 — physical paths moved from this array into the JSON registry so
#   registry data lives in a registry file and the zsh stays a clean executive.)
#
# folder layout is 1:1 on office and home; paths are identical on both hosts.
# companion: reposoma/registry/index.md — logical project map; projects.json holds physical paths.
# rule: source this file; do NOT hard-code these paths elsewhere.

typeset -gA TEMPLE_PROJECT_MAP
TEMPLE_PROJECT_MAP=(
HEADER
  jq -r '.projects | to_entries[] | "  [\(.key)]=\"\(.value)\""' "$SRC"
  cat <<'FOOTER'
)

# temple-project-root <project-name>
# Resolves a logical project name to its repo-root on this host.
# Exits non-zero and prints to stderr if unknown.
temple-project-root() {
  local name="$1"
  local root="${TEMPLE_PROJECT_MAP[$name]}"
  if [[ -z "$root" ]]; then
    print -u2 "temple-project-map: unknown project '$name' on host ${MACHINE_NAME:-unknown}"
    return 1
  fi
  if [[ ! -d "$root" ]]; then
    print -u2 "temple-project-map: project '$name' maps to '$root' but directory not found on this host"
    return 2
  fi
  print -- "$root"
}
FOOTER
}

case "$MODE" in
  stdout) render ;;
  check)
    if diff -q <(render) "$OUT" >/dev/null 2>&1; then
      echo "gen-temple-map: up to date"
    else
      echo "gen-temple-map: DRIFT — $OUT differs from projects.json (deploy will regenerate)" >&2
      exit 3
    fi ;;
  write)
    tmp="$(mktemp)"; render > "$tmp"; mv "$tmp" "$OUT"
    echo "gen-temple-map: regenerated $(basename "$OUT") from projects.json ($(jq '.projects|length' "$SRC") projects)" ;;
esac
