#!/usr/bin/env zsh
# zsh-orphans.zsh — deployed-vs-source drift reporter for the zsh tree
#
# WHY THIS EXISTS
#   deploy.sh rsyncs zsh/ WITHOUT --delete. Nothing removed from source is ever
#   removed from the machine, so ~/.config/zsh is not a projection of ia-sync/zsh —
#   it is an ACCRETION: the union of every state the source has ever been in.
#   First measured 2026-08-25 on home: 120 source files, 155 deployed, 37 orphans.
#
# WHY IT ONLY REPORTS
#   Plain `rsync --delete` would destroy the shell: the deployed `config.zsh` comes
#   from `config.home.zsh` and is rsync-EXCLUDED, so --delete reads it as an orphan.
#   Same for .env/ (secrets), .claude/, normalizer.py, and every log.
#   Beyond that: the classification below is a MAP, and maps in this tree have a
#   demonstrated record of being wrong in BOTH directions (2026-08-25 — AGENTS.md
#   claimed system/browser.zsh "never existed"; it was on disk. It listed five files
#   as "Maxwell must verify"; all five were live). An auto-deleter driven by a wrong
#   map deletes load-bearing files. So: this prints. A human decides.
#
# USAGE
#   zsh ~/.config/zsh/blessings/zsh-orphans.zsh
#   IA_SYNC_ZSH=/path/to/zsh zsh .../zsh-orphans.zsh    # override source tree
#
# Report-only by contract. It has no delete path, by design, at any flag.

emulate -L zsh
setopt no_unset pipe_fail extended_glob glob_dots
# glob_dots is REQUIRED: without it zsh's **/* skips dotfiles, so .env/ and
# .claude/ vanish from the comparison silently. A drift reporter that omits part
# of the tree is worse than none. .git/ is filtered explicitly below instead.

typeset SRC="${IA_SYNC_ZSH:-$HOME/ia-sync/zsh}"
typeset DEP="${HOME}/.config/zsh"

if [[ ! -d "$SRC" ]]; then
  print -u2 "zsh-orphans: source tree not found: $SRC"
  print -u2 "  (set IA_SYNC_ZSH if ia-sync lives elsewhere on this host)"
  exit 1
fi
if [[ ! -d "$DEP" ]]; then
  print -u2 "zsh-orphans: deployed tree not found: $DEP"
  exit 1
fi

# ---------------------------------------------------------------------------
# POLICY — the only part you edit.
#
# KEEP_GLOBS : machine-local by design. Deployed-only is CORRECT for these;
#              they must never be reported as removable.
# KILL_GLOBS : known-safe classes. Deployed-only is always litter here.
#
# Every entry moved from UNKNOWN into one of these lists makes the next run
# quieter. UNKNOWN is meant to shrink toward zero over time.
# ---------------------------------------------------------------------------
typeset -a KEEP_GLOBS KILL_GLOBS

KEEP_GLOBS=(
  'config.zsh'                          # deployed from config.<machine>.zsh (rsync-excluded)
  '.zshrc'                              # deployed from zshrc.<machine>
  '.env'                                # secrets dir — never in repo (sync.deny)
  '.env/*'
  '.claude'                             # machine-local settings
  '.claude/*'
  '*.log'                               # runtime logs
  'archive'                             # machine-local parked history
  'archive/*'
  '*/journal.*.jsonl'                   # runtime journals (archx etc.)
  'temple-project-map.zsh'              # GENERATED by registries/gen-temple-map.sh at deploy
  # --- load-bearing on HOME until it migrates to inline PROJECT_* exports.
  # --- Deleting either takes home's project switcher with it. See ia-sync AGENTS.md.
  'normalizer.py'
  'harness.machine-project-registry.json'
)

KILL_GLOBS=(
  '*.bak-*'                             # deploy.sh copy_file() exhaust — unbounded
  '*.backup'
  '*.stale-*'
  'substrate.*'                         # sync.deny'd cross-machine contamination
)

# Never compared at all — VCS internals would flood UNKNOWN with noise.
typeset -a SKIP_GLOBS
SKIP_GLOBS=('.git' '.git/*')

# ---------------------------------------------------------------------------

_zo_list() {
  # $1 = tree root. Emits relative paths of regular files, minus SKIP_GLOBS.
  local root="$1" f g skip
  local -a out
  for f in ${(f)"$(cd "$root" && print -rl -- **/*(.N))"}; do
    skip=""
    for g in $SKIP_GLOBS; do
      [[ "$f" == ${~g} ]] && { skip=1; break; }
    done
    [[ -z "$skip" ]] && out+=("$f")
  done
  print -rl -- ${(o)out}
}

typeset -a src_files dep_files
src_files=(${(f)"$(_zo_list "$SRC")"})
dep_files=(${(f)"$(_zo_list "$DEP")"})

typeset -a orphans missing
orphans=(${dep_files:|src_files})   # deployed but not in source
missing=(${src_files:|dep_files})   # in source but not deployed

typeset -a bucket_keep bucket_kill bucket_unknown
typeset f g matched

for f in $orphans; do
  matched=""
  for g in $KEEP_GLOBS; do
    if [[ "$f" == ${~g} ]]; then matched="keep"; break; fi
  done
  if [[ -z "$matched" ]]; then
    for g in $KILL_GLOBS; do
      if [[ "$f" == ${~g} ]]; then matched="kill"; break; fi
    done
  fi
  case "$matched" in
    keep) bucket_keep+=("$f") ;;
    kill) bucket_kill+=("$f") ;;
    *)    bucket_unknown+=("$f") ;;
  esac
done

print -- "zsh-orphans · $(date +%Y-%m-%d) · host=${MACHINE_NAME:-unknown}"
print -- "source   : $SRC  (${#src_files} files)"
print -- "deployed : $DEP  (${#dep_files} files)"
print -- ""

print -- "KEEP — deployed-only by design (${#bucket_keep})"
if (( ${#bucket_keep} )); then
  for f in $bucket_keep; do print -- "    $DEP/$f"; done
else
  print -- "    (none)"
fi
print -- ""

print -- "KILL — known-safe litter (${#bucket_kill})"
if (( ${#bucket_kill} )); then
  for f in $bucket_kill; do print -- "    $DEP/$f"; done
else
  print -- "    (none)"
fi
print -- ""

print -- "UNKNOWN — needs a human (${#bucket_unknown})"
if (( ${#bucket_unknown} )); then
  for f in $bucket_unknown; do print -- "    $DEP/$f"; done
  print -- ""
  print -- "  Each of these is either machine-local (add to KEEP_GLOBS) or dead"
  print -- "  (add to KILL_GLOBS, or quarantine it). Trace before deciding:"
  print -- "    grep -rn '<basename>' --include='*.zsh' --include='*.sh' $DEP"
else
  print -- "    (none — policy covers every orphan)"
fi
print -- ""

if (( ${#missing} )); then
  print -- "NOT DEPLOYED — in source, absent on this host (${#missing})"
  print -- "  Expected for host-specific files (config.*.zsh, zshrc.*) — anything else"
  print -- "  means a deploy has not run since that file was added."
  for f in $missing; do print -- "    $SRC/$f"; done
  print -- ""
fi

if (( ${#bucket_kill} )); then
  typeset q="/tmp/zsh-prune-$(date +%Y-%m-%d)"
  print -- "Quarantine the KILL bucket (two-phase: move now, purge after a clean shell):"
  print -- ""
  print -- "  mkdir -p $q && cd $DEP && for f in ${bucket_kill}; do"
  print -- "    mkdir -p \"$q/\$(dirname \$f)\" && mv \"\$f\" \"$q/\$f\"; done"
  print -- ""
  print -- "  # verify, then purge:"
  print -- "  zsh -n $DEP/config.zsh && zsh -n $DEP/ai/base.zsh && echo OK"
  print -- "  # rm -rf $q     <- only after a fresh shell comes up clean"
fi

exit 0
